### ISSUE TITLE
A question about validate difficulty

### ISSUE THREAD

**Issue by Elvenisboy** [ethereumjs/ethereumjs-block#33]
When validate a block difficultly header use:
<code>
 return dif.cmp(new BN(this.difficulty)) === 0>
</code>

emmm, if a difficulty is current, this.difficulty should be equal to dif.
So code should be

<code>
 return dif.cmp(new BN(this.difficulty)) === 1
</code>

Why we you zero in header code?

**Comment by jwasinger** [comment]
The source code for the `cmp` function:
```
        /*
         * Return
         * 1 if the value of this BigNumber is greater than the value of BigNumber(y, b),
         * -1 if the value of this BigNumber is less than the value of BigNumber(y, b),
         * 0 if they have the same value,
         * or null if the value of either is NaN.
         */
        P.comparedTo = P.cmp = function ( y, b ) {
            id = 1;
            return compare( this, new BigNumber( y, b ) );
        };
```

**Comment by Elvenisboy** [comment]
okay, I get it. Thank you☺️☺️☺️

**Comment by jwasinger** [comment]
You're welcome :)

**Comment by axic** [comment]
@jwasinger `.cmp` should be replaced with `.lt`, `.lte`, `.eq`, `.gt`, `.gte` for readability in all ethereumjs code.
