### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by benjamincburns** [ethereumjs/ethereumjs-block#43]
It'd be nice if this and other commonly-used ethereumjs projects had `*.d.ts` files so that they could be used with TypeScript projects.

**Comment by benjamincburns** [comment]
I should have said in the description - I'm working on PRs for this, as I'm in the process of converting `ganache-core` over to TypeScript.

**Comment by holgerd77** [comment]
Hi @benjamincburns, this already was a topic on two or three other repos lately and we had some contribution starts on this (e.g. https://github.com/ethereumjs/ethereumjs-wallet/pull/30).

We have a bit the problem that none of the current maintainers seem to have used TypeScript before (including me) and neither have a good feeling for it nor would be able to maintain. That slows things down a bit.

You're welcome to open a PR on this though, we would just have to discuss how to handle this and you maybe have to explain a bit more than you might be used to. 😀

**Comment by alcuadrado** [comment]
Fixed by #72 🚀
