### ISSUE TITLE
Typescript migration

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-block#71]
Not having types in this library was by far the major source of bugs I had when working with the VM. I think we should consider migrating it.

**Comment by holgerd77** [comment]
Yes, this is one of the last ones missing. @s1na not sure, did you once say that you already did some work on that?

**Comment by s1na** [comment]
Agreed. Well, when we first started "The Great Migration" (:smile:) I spent an hour or so on migrating this library, but stopped soon because it depended on other libraries and they didn't have typedefs yet. So no, I don't have anything useful, we'll have to start from scratch.

**Comment by alcuadrado** [comment]
I'm working on this migration. It's a little more complicated than I expected, but not terrible.

One thing that I'm wondering is if we should migrate and keep these files:

1. https://github.com/ethereumjs/ethereumjs-block/blob/2c3908e5bbb6c9c94aeb5547a779295433f42545/from-rpc.js
2. https://github.com/ethereumjs/ethereumjs-block/blob/2c3908e5bbb6c9c94aeb5547a779295433f42545/header-from-rpc.js

They seem super out of place to me. None of the other main libraries has anything to do with the RPC format.

**Comment by s1na** [comment]
My guess is that those functions are in use by MetaMask. Let's migrate them along but create an issue to discuss their deprecation.

**Comment by alcuadrado** [comment]
Makes sense, I'll do that/
