### ISSUE TITLE
Browser tests are usually hitting Travis log size limit

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-block#78]
Latest runs of `test:browser` have presented failures due to huge log output ([when it hits 4MB mark](https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded)).

`The job exceeded the maximum log length, and has been terminated.`

I believe that simplifying the test reporting using less bytes as output can solve it.

**Comment by alcuadrado** [comment]
I was also hit by this and [tried my best](https://github.com/ethereumjs/ethereumjs-block/commit/1723f9bff8a4ff7af2647a5c7c2c88fa532077c1) to reduce the size of the tests' output. I should have opened an issue for future reference.

I don't know much about karma, so there may be lots of room for improvement.

**Comment by evertonfraga** [comment]
Fixed by #86
