### ISSUE TITLE
[EIP 2384]: Implement difficulty bomb delay

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-block#79]
[EIP 2384](https://github.com/ethereum/EIPs/pull/2384/) is still in draft mode, but should escalate to a final state quickly, as the target date is mid-January.

Requirements:
- [x] A fork needs a name, to implement in `-common`. Will use `EIP-2384` for now
- [x] Block number from EIP
- [x] [Difficulty tests from ethereum/tests](https://github.com/ethereum/tests/pull/662/files)
- [x] Copy tests to this repo and add relevant metadata (source, date, commit and hash)

**Comment by holgerd77** [comment]
For reference here the difficulty bomb implementation for `Constantinople`: https://github.com/ethereumjs/ethereumjs-block/pull/54

@evertonfraga I am not following the discussion closely, is this rather planned for the `Berlin` HF, will this be an own HF or is this not decided yet (optimally directly link to the discussion)?
