### ISSUE TITLE
Type interface for Block

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-block#83]
It would be nice if we had an exportable type for `Block`.

We are using [any](https://github.com/ethereumjs/ethereumjs-blockchain/blob/0cf409e8c5d9f9e36a2d1ef7d584dafeafae35d3/src/index.ts#L23) in `ethereumjs-blockchain` and it's no fun.

**Comment by holgerd77** [comment]
`TypeScript` version of this library is merged to `master´ but not released yet, see discussion here https://github.com/ethereumjs/ethereumjs-block/pull/74.

**Comment by ryanio** [comment]
Gotcha, thanks!
